# Generated by Django 4.2.6 on 2023-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(blank=True, max_length=50)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('graphics', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
