# Generated by Django 4.2.6 on 2023-12-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
