# Generated by Django 4.2.6 on 2023-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_laptop_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
