# Generated by Django 4.2.6 on 2023-12-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_picture_alter_laptop_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=50)),
                ('advantage', models.TextField(blank=True, max_length=50)),
                ('disadvantage', models.TextField(blank=True, max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
