# Generated by Django 4.2.6 on 2023-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_programming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programming',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programming',
            name='advantage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programming',
            name='disadvantage',
            field=models.TextField(blank=True),
        ),
    ]
