# Generated by Django 4.2.6 on 2023-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_picture_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(blank=True)),
                ('advantage', models.TextField(blank=True)),
                ('disadvantage', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
