# Generated by Django 4.2.6 on 2023-12-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frontend_Framework',
        ),
    ]
