# Generated by Django 4.2.6 on 2023-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_delete_frontend_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Languages', models.CharField(max_length=50, null=True)),
                ('Features', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
