# Generated by Django 4.2.6 on 2023-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_ide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='IDE',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
