# Generated by Django 4.2.6 on 2023-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_ide_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='Languages',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
