# Generated by Django 4.2.6 on 2023-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_ide_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='Languages',
            field=models.TextField(null=True),
        ),
    ]
