# Generated by Django 4.2.6 on 2024-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_ide_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
