# Generated by Django 4.2.6 on 2024-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_laptop_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='date_created',
        ),
        migrations.AddField(
            model_name='framework',
            name='images',
            field=models.ImageField(blank=True, upload_to='framework/'),
        ),
        migrations.AddField(
            model_name='frontend_stack',
            name='images',
            field=models.ImageField(blank=True, upload_to='frontend/'),
        ),
        migrations.AddField(
            model_name='ide',
            name='images',
            field=models.ImageField(blank=True, upload_to='ide/'),
        ),
        migrations.AddField(
            model_name='programming_language',
            name='images',
            field=models.ImageField(blank=True, upload_to='language/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='images',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
