# Generated by Django 4.2.6 on 2024-02-01 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_delete_picture_remove_laptop_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='images',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
