# Generated by Django 4.2.6 on 2024-02-01 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_laptop_date_created_alter_laptop_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='frontend_stack',
            name='release_date',
        ),
        migrations.AddField(
            model_name='framework',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='frontend_stack',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ide',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programming_language',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
