# Generated by Django 4.2.6 on 2024-02-01 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_framework_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('classification_type', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.laptop')),
            ],
        ),
    ]
