# Generated by Django 4.2.6 on 2024-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='date_created',
        ),
    ]
